version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: python main.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./server/temp_files:/app/temp_files
      - ./server/temp_exports:/app/temp_exports
      - ./auth.db:/app/auth.db
    networks:
      - app-network


  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: python main.py
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge